spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dbsghdla1!
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
external:
  apartment-api:
    path: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    service-key: 7tqj91v3gM7kFRZZSCrTUG1WdsedUh0rJewmEb%2FJYZtrztrrX1uJs9uxJeDxR%2BxHKJmNYRw4cvH1fybKqlY%2FGA%3D%3D

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2